services:
  - type: web
    name: web-scraper-api
    runtime: python
    envVars:
      - key: GROQ_API_KEY
        value: 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  # REPLACE WITH SECRETS GROUP!
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind :$PORT main:app  # Corrected entry point
    healthCheckPath: /